services:
  pgdatabase:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - "dtc_postgres:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - "pgadmin_data:/var/lib/pgadmin:rw"
    ports:
      - "8080:80"
    depends_on:
      - pgdatabase
    
volumes:
  dtc_postgres:
  pgadmin_data: